### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by dhararon** [viewflow/viewflow#151]
I was copying the code from website and when i try to run the server i had this problem

```python
Unhandled exception in thread started by <function wrapper at 0x10fdeeed8>
Traceback (most recent call last):
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/viewflow/models.py", line 8, in <module>
    from .fields import FlowReferenceField, TaskReferenceField, TokenField
  File "/Users/dhararon/Envs/dfv/lib/python2.7/site-packages/viewflow/fields.py", line 89
    class FlowReferenceField(models.CharField, metaclass=_SubfieldBase):
                                                        ^
SyntaxError: invalid syntax
```
I'm using this version: 
django-viewflow==0.10.1

**Comment by kmmbvnr** [comment]
That's correct.

Viewflow AGPL have only support for Python3

**Comment by TheSundar** [comment]
can't we use for python 2.7

**Comment by kmmbvnr** [comment]
Older versoon of pythpn available as paid option.

Viewflow Pro has support for Python 2.7, pre-build material frontend and extended nodes set including obsolete nodes and subprocess
