### ISSUE TITLE
Wrong id_flow_class in rendered viewset , for objects created via a flow

### ISSUE THREAD

**Issue by vsmanu** [viewflow/viewflow#202]
I have a couple of flows , I have also created view sets (material.frontend.views.ModelViewSet) for editing the objects created via flows.
But when I am editing through view set for the same object created via flow fails with a 500,

It fails at 
`Line 14 : app_label, flow_path = flow_strref.split('/')
`
in file python3.6/site-packages/viewflow/fields.py

When I checked UI, for my surprice , it is not the expected value,
`
<input id="id_flow_class" maxlength="250" name="flow_class" type="text" value="Create XXX YYYY Region">
`
So it is expecting the flow_class as APP/flowclass format.
What we are seeing instead is a space seperated name of the class with "Create" prefix.

`
Internal Server Error: /di_service_manager/region/1/change/
Traceback (most recent call last):
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/forms/forms.py", line 179, in is_valid
    return self.is_bound and not self.errors
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/forms/forms.py", line 174, in errors
    self.full_clean()
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/forms/forms.py", line 378, in full_clean
    self._post_clean()
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/forms/models.py", line 396, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/forms/models.py", line 60, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 838, in save_form_data
    setattr(instance, self.name, data)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/viewflow/fields.py", line 79, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/viewflow/fields.py", line 104, in to_python
    return import_flow_by_ref(value)
  File "/home/myHome/myDevWorkspace/venvs/fugu/lib/python3.6/site-packages/viewflow/fields.py", line 14, in import_flow_by_ref
    app_label, flow_path = flow_strref.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
`

The PIP freeze is : 
`
Django==2.0
django-extensions==2.0.5
django-filter==1.1.0
django-material==1.2.0
django-viewflow==1.2.0
pytz==2018.3
six==1.11.0
`

**Comment by kmmbvnr** [comment]
I don't think I would able to reproduce the issue using provided information. 

Probably you have something wrong in your code base.

**Comment by vsmanu** [comment]
Is that ok / meant to use the model classes extended from Process , with material viewsets ?
Will test and update you the same scenario with the HellowWorld demo project.

**Comment by vsmanu** [comment]
For a quick testing , I have done it with admin view, with project 
https://github.com/viewflow/cookbook.git
Module Path helloworld/demo

Just adding admin.py
`from django.contrib import admin
from .models import HelloWorldProcess
admin.site.register(HelloWorldProcess)`

And trying to edit an already created object , resulted in previous error.
So it is not about my UI / modules ;)

**Comment by kmmbvnr** [comment]
http://demo.viewflow.io/admin/viewflow/process/ ?

**Comment by kmmbvnr** [comment]
Basically, I think the problem that in your case process.flow_class contains an invalid value. It should be a correct reference to flow class.

Generally, it's a bad idea to allow to edit class names through viewset. You should not do that. Although, any other process field could be available.

**Comment by vsmanu** [comment]
But is there any direct way (best practice) for editing the objects created in a flow ?,
In my case even registered admin interface fails with same error.
OR
Is it meant to be failed ?

**Comment by jntsouza** [comment]
I`m getting the same error, could you please help me?
ValueError at /admin/proserv_process/budgetorderprocessteste1/28/change/
not enough values to unpack (expected 2, got 1)

    def import_flow_by_ref(flow_strref):
        """Return flow class by flow string reference."""
       ---> app_label, flow_path = flow_strref.split('/')
       return import_string('{}.{}'.format(get_app_package(app_label), flow_path))
flow_strref | 'Orçamento e Pedido'

**Comment by jntsouza** [comment]
I think I got the problem...
if you put readonly_fields on your admin.py causes this error while trying to change by the admin interface.

class BudgetOrderProcessAdmin(ProcessAdmin):
    icon = '<i class="material-icons">flag</i>'
    save_on_top = True
    ---> readonly_fields=[('total'), ('ipi_total')]

**Comment by jntsouza** [comment]
this way it worked for me:

readonly_fields=['total', 'ipi_total','flow_class', 'status', 'finished']
