### ISSUE TITLE
[PRO] ImportError with Django 3

### ISSUE THREAD

**Issue by fwip** [viewflow/viewflow#276]
Error:
```$ ./manage.py
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/viewflow/frontend/apps.py", line 43, in ready
    autodiscover_modules('flows', register_to=self)
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/stambot/app/meret/intake/flows.py", line 3, in <module>
    from viewflow.rest import flow, views
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/viewflow/rest/flow.py", line 2, in <module>
    from . import activation, views
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/viewflow/rest/views/__init__.py", line 5, in <module>
    from .chart import FlowChartView
  File "/home/stambot/.virtualenv/app/lib64/python3.6/site-packages/viewflow/rest/views/chart.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
```

requirements.txt:
```Django==3.0.5
gunicorn==20.0.4
djangorestframework==3.11.0
django-filter==2.2.0
model-bakery==1.1.0
django-rest-swagger==2.2.0
django-guardian==2.2.0
django-reversion==3.0.7
django-environ==0.4.5
whitenoise==5.0.1
--extra-index-url=https://pypi.viewflow.io/[redacted]/simple/
django-material-pro
django-viewflow-pro
```

Suggest changing line 3 of `viewflow/rest/views/chart.py` to `import six`.

**Comment by fwip** [comment]
More information: https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by fwip** [comment]
Ah, I see that Django 3 isn't listed as compatible yet. Is this on the roadmap?
