### ISSUE TITLE
Changing Process model instance value in admin causes error

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#285]
When I tried to change the `to_size` value in admin I got the following error:

```
Traceback (most recent call last):
  File "/srv/www/pmas/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1554, in _changeform_view
    form_validated = form.is_valid()
  File "/srv/www/pmas/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/srv/www/pmas/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/srv/www/pmas/lib/python3.6/site-packages/django/forms/forms.py", line 383, in full_clean
    self._post_clean()
  File "/srv/www/pmas/lib/python3.6/site-packages/django/forms/models.py", line 398, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/srv/www/pmas/lib/python3.6/site-packages/django/forms/models.py", line 60, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "/srv/www/pmas/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 859, in save_form_data
    setattr(instance, self.name, data)
  File "/srv/www/pmas/lib/python3.6/site-packages/viewflow/fields.py", line 79, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/srv/www/pmas/lib/python3.6/site-packages/viewflow/fields.py", line 104, in to_python
    return import_flow_by_ref(value)
  File "/srv/www/pmas/lib/python3.6/site-packages/viewflow/fields.py", line 14, in import_flow_by_ref
    app_label, flow_path = flow_strref.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

my models
```python
class BaseChangeRequest(Process):
    # reference mergeportal customer slug
    customer_code = models.CharField(max_length=25)
    requester_email = models.EmailField()
    vmh = models.CharField(max_length=255)
    node = models.CharField(max_length=25, blank=False)
    vmid = models.IntegerField()
    vm_name = models.CharField(max_length=25)
    approved = models.NullBooleanField(blank=False, choices=((False, 'No'), (True, 'Yes')))
    decided_by = models.ForeignKey(get_user_model(), null=True, on_delete=models.DO_NOTHING)
    decision_reason = models.TextField(blank=True)

    note = models.TextField(blank=True)

    class Meta:
        abstract = True


class DiskSizeChangeRequest(BaseChangeRequest):
    disk = models.CharField(max_length=25)
    disk_description = models.CharField(max_length=255)
    tier = models.SmallIntegerField(null=True)
    from_size = models.IntegerField(null=True)
    to_size = models.IntegerField()
```

**Comment by kmmbvnr** [comment]
Thank you for the detailed report, this caused by flow_class field, that needs to be set read_only to work in the django admin

For quick customization, you could just extend ProcessAdmin, and override required attributes
https://github.com/viewflow/viewflow/blob/master/viewflow/admin.py#L22

**Comment by variable** [comment]
Thanks that worked.
