### ISSUE TITLE
I updated and am now getting ModelAdmin and TaskAdmin errors

### ISSUE THREAD

**Issue by chrisJuresh** [viewflow/viewflow#434]
My admin.py files dont have anything viewflow related in them...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chris/rcr/backend/venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/chris/rcr/backend/venv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/chris/rcr/backend/venv/lib/python3.11/site-packages/django/core/management/base.py", line 563, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'viewflow.workflow.admin.TaskAdmin'>: (admin.E040) ModelAdmin must define "search_fields", because it's referenced by TaskAdmin.autocomplete_fields.
<class 'viewflow.workflow.admin.TaskInline'>: (admin.E040) ModelAdmin must define "search_fields", because it's referenced by TaskInline.autocomplete_fields.

System check identified 2 issues (0 silenced).

**Comment by kmmbvnr** [comment]
Have you have custom admin for the User model?

Django Viewflow uses autocomplete_fields for the  user-related owner fields in Task and Process models. This requires to have some search_fields on the custom User admin https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields

**Comment by kmmbvnr** [comment]
I removed autocomplete fields to avoid clashes 01e2a0edc6e0d7c543c12bb6915b3837152aff56
