### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by zhoudaxia233** [viewflow/viewflow#462]
`django-viewflow==2.2.5`
`Django==4.2.14`

I'm using Python3.8, below is the stack trace:

```
backend_1        | Exception in thread django-main-thread:
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
backend_1        |     self.run()
backend_1        |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
backend_1        |     self._target(*self._args, **self._kwargs)
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
backend_1        |     fn(*args, **kwargs)
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
backend_1        |     autoreload.raise_last_exception()
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
backend_1        |     raise _exception[1]
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 394, in execute
backend_1        |     autoreload.check_errors(django.setup)()
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
backend_1        |     fn(*args, **kwargs)
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
backend_1        |     apps.populate(settings.INSTALLED_APPS)
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
backend_1        |     app_config.import_models()
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
backend_1        |     self.models_module = import_module(models_module_name)
backend_1        |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
backend_1        |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1        |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
backend_1        |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
backend_1        |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
backend_1        |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1        |   File "/home/python/app/src/ordering/order/models.py", line 7, in <module>
backend_1        |     from viewflow import fsm
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/viewflow/fsm/__init__.py", line 17, in <module>
backend_1        |     from .viewset import FlowViewsMixin
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/viewflow/fsm/viewset.py", line 12, in <module>
backend_1        |     from viewflow.urls import ViewsetMeta
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/viewflow/urls/__init__.py", line 3, in <module>
backend_1        |     from .base import BaseViewset, IndexViewMixin, Viewset, ViewsetMeta, route
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/viewflow/urls/base.py", line 69, in <module>
backend_1        |     class BaseViewset:
backend_1        |   File "/home/python/.local/lib/python3.8/site-packages/viewflow/urls/base.py", line 130, in BaseViewset
backend_1        |     args: Optional[list[Any]] = None,
backend_1        | TypeError: 'type' object is not subscriptable
```

Seems like version 2.2.5 doesn't support Python 3.8.

**Comment by kmmbvnr** [comment]
Thank you for the report, inded the typing decaration does not works in python 3,8

Fixed at a24a8d0437bc6085faf071075dc368bab5cd4078
