### ISSUE TITLE
NSubprocess Usage

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/viewflow#470]
Hi,
it seems to have a bug with subprocess task
![image](https://github.com/user-attachments/assets/88ce20fb-e904-4e98-a176-530da6891981)

Best regards

**Comment by Tooblippe** [comment]
There is not enough information in your report to understand or analyse the error? 
Maybe you could provide the full stack trace and the code of the process that was parent to this activation and error.

**Comment by D0wn3r** [comment]
```
Traceback (most recent call last):
  File "****-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "******-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "*****-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/flow/utils.py", line 51, in view
    return origin_view(request, *args, **kwargs)
  File "*******-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "*******-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "******-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/views/generic/edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "******-zbRiz2ay-py3.10/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "******-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/flow/views/create.py", line 32, in form_valid
    self.request.activation.execute()
  File "*********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/fsm/base.py", line 228, in __call__
    return self._func(self._instance, *args, **kwargs)
  File "*******-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/nodes/start.py", line 78, in execute
    super().execute.original()
  File "*********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/fsm/base.py", line 196, in original
    return self._func(self._instance, *args, **kwargs)
  File "************-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/nodes/start.py", line 40, in execute
    self.activate_next()
  File "*********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/fsm/base.py", line 228, in __call__
    return self._func(self._instance, *args, **kwargs)
  File "*********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/activation.py", line 275, in activate_next
    self._activate_next(activations)
  File "********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/activation.py", line 241, in _activate_next
    current_activation.activate()
  File "***********-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/fsm/base.py", line 228, in __call__
    return self._func(self._instance, *args, **kwargs)
  File "************-zbRiz2ay-py3.10/lib/python3.10/site-packages/viewflow/workflow/nodes/subprocess.py", line 204, in activate
    self.flow_task.start_subprocess_task.run(
AttributeError: 'Job' object has no attribute 'run'
```

**Comment by kmmbvnr** [comment]
A process could be started with some start node. Other nodes just continues to work on an exiting process.

You can't use celery.Job as a node to start subprocess. Use flow.StartHandle instead. And in the start handle you would able to link passed process parameters to process data, to be used later by Job node

```python
class MainFlow(flow.Flow)
    process_events = flow.NSubprocess(
        Subflow.as_subprocess,
        subitem_source=lambda process: [
            (process.seed, event_data) # list of items 
            for event_data in process.parsed_response["events"]
        ],
    ).Next(this.end)

class Subflow(flow.Flow):
    as_subprocess = flow.StartHandle(this.start_process).Next(this.a_job)

    def start_process(self, activation, item):
        activation.process.seed = item[0] # deconstruct process specific item
        activation.process.event_data = item[1]
```
